### ISSUE TITLE
BDD tesztek készítése

### ISSUE THREAD

**Issue by timarbende** [BME-MIT-IET/iet-hf2021-aviato#11]
BDD tesztek készítése Cucumber rendszerrel

**Comment by timarbende** [comment]
Eddigi commitok:
https://github.com/BME-MIT-IET/iet-hf2021-aviato/commit/334d9f55eccafff590d5280ade2fe73ee22e9974
https://github.com/BME-MIT-IET/iet-hf2021-aviato/commit/fd044a70314422ef8a963a6e9e8d865cbd24b6e4
https://github.com/BME-MIT-IET/iet-hf2021-aviato/commit/8febc15454dd81aff56c2abf3e17cc140349e47c
https://github.com/BME-MIT-IET/iet-hf2021-aviato/commit/0d0b9967c724f88d4f8ac0624b7209e6598f08f9

**Comment by timarbende** [comment]
Eddig implementált tesztek:
- Egyszerű lépés
- Sorozatos lépés
- Összes lépési lehetőség elhasználása
- Tárgy felvétele
- Tárgy felvételének megtagadása mozgási lehetőség hiánya miatt
- Tárgy felvétele csak akkor lehetséges, ha a mező tiszta
-  Mező megtisztítása
- Evés visszahozza a testhőt
- Csak akkor lehet enni, ha van még rá lépés
- Maximális élet felső korlátja
- Vízbe esés instabil jégtábláról egyedül
- Vízbe esés instabil jégtábláról csoportosan

**Comment by timarbende** [comment]
Új tesztek:
- Lépés csak akkor lehetséges, ha a mezők szomszédosak
- Iglu építés
- Mező megtisztításának megtagadása mozgási lehetőség hiánya miatt
- Sátor építés
- Egyszerű medve mozgás
- Medve támadás védelem nélkül
- Medve támadás igluval
- Medve támadás sátorral

**Comment by tsz99** [comment]
eddigi commitok

fd044a70314422ef8a963a6e9e8d865cbd24b6e4
8febc15454dd81aff56c2abf3e17cc140349e47c
0d0b9967c724f88d4f8ac0624b7209e6598f08f9

**Comment by tsz99** [comment]
81065cbaf072af5d20658dde88fadd5c896752d4
e72d3956c4f6b3997f3c229f95c36b830762d7cc
60a6d28fe15b62c3dd3687615465c653649d6041
2e25e09c446d46e4c649288845a6666f992e022b
