### ISSUE TITLE
JUnit tesztek

### ISSUE THREAD

**Issue by bitman07** [BME-MIT-IET/iet-hf2021-aviato#14]
Egységtesztek készítése
Elvégzendő feladatok:
@DDorian13:
- Tesztpályák készítése
- Iglu megvéd a medvétől
- Sikeres lépés
- Lapát sikeres használata
- Kutató sikeres felderítés
- Kutató sikertelen felderítés (nem szomszédos mező)

@bitman07:
- Tesztpálya sikeres felépítése (megfelelő szomszédok, teherbírás stb.)
- Sátor lerombolódik egy kör után
- Épület megvéd a hóeséstől
- Sikertelen tárgy felvétel (hó alatt van)
- Eszkimó sikertelenül épít (nincs felderítve)
- Lyukba esésnél felderítődik a mező

**Comment by DDorian13** [comment]
Végleges commitok:
https://github.com/BME-MIT-IET/iet-hf2021-aviato/commit/fa74efd9c5bd117beb7bbe884d0ab4699173e4b7 -- @DDorian13 
https://github.com/BME-MIT-IET/iet-hf2021-aviato/commit/103e55ee77bb554363824354514abe60370bb618 -- @bitman07
